name: CI Github Pages
on:
  #监听push操作
  push:
    branches:
      - main # 这里只配置了main分支，所以只有推送main分支才会触发以下任务
jobs:
  # 任务ID
  build-and-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 官方action，将代码拉取到虚拟机
      - name: Checkout  ️ 
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # 这个设置很重要，尤其是在部署到 public repository 时

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        run: |
          npm install -g pnpm
          echo "Verify pnpm version"
          pnpm -v



      - name: Add pnpm to PATH
        run: echo "$(npm prefix -g)/bin" >> $GITHUB_PATH


      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run docs:build

      - name: Deploy   # 部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          # branch: gh-pages # 部署后提交到那个分支
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./site/docs/.vitepress/dist # 这里填打包好的目录名称